### ISSUE TITLE
pt_export not accepting SDCtool -argument

### ISSUE THREAD

**Issue by janikat** [sdcTools/protoTestCensus#1]
Working with R 3.5.1
I am trying to follow the instructions in CellKey/SAS but data export as in example: pt_export(result, file="C:/ptable_d2_v108_js1.csv", SDCtool="SAS") doesn't work for me. I should have updated versions of  "sdcTools/ptable" and "sdcTools/cellKey". Should I update or download something else as well. 

I can work this out in SAS but for future use it would be nice to find out what went wrong.

**Comment by tenderle** [comment]
@janikat, which version of the `ptable`-package do you use? 
```
library(ptable)
packageVersion("ptable")
```
I suggest, you have an older version (< 0.2.0 or even < 0.1.14). The argument `SDCtool="SAS"` is available since version 0.1.14. Please install the new version following the [instructions](https://github.com/sdcTools/protoTestCensus/tree/master/CellKey/ptable).

However, if you already have installed 0.1.14, please describe the error more detailed.

**Comment by janikat** [comment]
@tenderle Thank you! 
I had version 0.1.11! After installing the new version (I had to reinstall devtools as well) it is working fine.
